# Generated by Django 4.1.1 on 2022-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_small1', models.ImageField(null=True, upload_to='Banner Images1')),
                ('banner_small2', models.ImageField(null=True, upload_to='Banner Images2')),
                ('banner_small3', models.ImageField(null=True, upload_to='Banner Images3')),
                ('banner_small4', models.ImageField(null=True, upload_to='Banner Images4')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='Slider Images')),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
            },
        ),
    ]
