# Generated by Django 4.1.1 on 2022-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
