# Generated by Django 4.1.1 on 2022-11-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogbanner_remove_blog_image_blog_image_small_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
