# Generated by Django 4.1.1 on 2022-11-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_category_delete_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
