# Generated by Django 4.1.1 on 2022-09-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productversion_code_productversion_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.productcategory', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_categories', to='products.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.productversion', verbose_name='Product Version'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='code',
            field=models.BigIntegerField(default=0, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_version/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Is New'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Is Sale'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='is_stock',
            field=models.BooleanField(default=True, verbose_name='Is Stock'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='property_options',
            field=models.ManyToManyField(blank=True, related_name='product_property_options', to='products.propertyoption', verbose_name='Property Options'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='sale_percent',
            field=models.IntegerField(default=0, verbose_name='Sale Percent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertyoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertyoption',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_option', to='products.property', verbose_name='Property'),
        ),
    ]
