# Generated by Django 4.1.1 on 2022-09-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productversion_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_version', to='products.brand', verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
