# Generated by Django 4.1.1 on 2022-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productversion_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='cover_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_version/', verbose_name='Cover Image 2'),
        ),
    ]
