# Generated by Django 4.1.1 on 2022-09-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productversion_cover_image_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product Version', 'verbose_name_plural': 'Product Versions'},
        ),
    ]
