# Generated by Django 4.1.1 on 2022-09-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_version', to='products.brand', verbose_name='Brand'),
        ),
    ]
