# Generated by Django 4.1.1 on 2022-09-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productversion_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='brand',
        ),
    ]
