# Generated by Django 4.1.1 on 2022-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
