# Generated by Django 4.1.1 on 2022-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcategory_name_en_productcategory_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final Price'),
        ),
    ]
