# Generated by Django 4.1.1 on 2022-12-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productversion_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_az',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.productcategory', verbose_name='Parent'),
        ),
    ]
